#!/bin/zsh

if [[ $# -lt 1 ]]
then
   print "Usage: ${0:t} username [repo|--] [branch]"
   print "\nusername, repo and branch are taken from GitHub"
   print "\nif no repo is given, or if '--' is used, the username is used in its place"
   print "\nif no branch is give, the default branch from Github is used"
   exit 1
fi


if [[ ("$2" = "") || ("$2" = "--") ]]
then
   GIT_URL="$1/$1"
else
   GIT_URL="$1/$2"
fi

if [[ "$3" != "" ]]
then
   GIT_ARGS="-b $3"
fi

git clone git@github.com:$GIT_URL $GIT_ARGS
