#!/bin/zsh

if [[ $# -lt 1 ]]
then
   print "Usage: ${0:t} username [repo|--] [branch]"
   print "\nusername, repo and branch are taken from GitHub"
   print "\nif no repo is given, or if '--' is used, the username is used in its place"
   print "\nif no branch is give, the default branch from Github is used"
   exit 1
fi

if [[ "$1" =~ "/" ]]
then
  GIT_URL="$1"
  shift
elif [[ ("$2" = "") || ("$2" = "--") ]]
then
  GIT_URL="$1/$1"
  shift
else
  GIT_URL="$1/$2"
  shift 2
fi

if [[ "$1" != "" ]]
then
  GIT_BRANCH="-b $1"
  shift
fi

pushd ~/gh_repos/
git clone git@github.com:${GIT_URL} ${=GIT_BRANCH} ${=*}
popd
