#!/bin/zsh
# Used to start streaming specific music from my library to be used with S.O.A.P
if [[ "$VLC" == "" ]]
then
	export VLC=$(which cvlc)
fi
${VLC} ${*} --sout-keep --sout '#transcode{acodec=vorb,ab=128,channels=2}:duplicate{dst=std{access=http,mux=ogg,dst=129.21.50.7:9001}}'
