#!/usr/bin/python3.2

# Author Anthony Gargiulo
# Last modified on Wed Jan 18 02:06:33 EST 2012
responses = []
correctAnswers = []

response = ""
quesNum = 1
correctAnswer = ""

print("Enter your responses one at a time. After the last response, enter 'end' to move on.")

while True:
	response = input(quesNum + ": ")
	if response == "end":
		break
	responses.append(response)
	quesNum += 1

print("Enter the correct answers one at a time. After the last answer, enter 'end' to move on.")

quesNum = 0 #reset the question count

while True:
	correctAnswer = input(quesNum + ": ")
	if correctAnswer == "end":
		break
	correctAnswers.append(correctAnswer)
	quesNum += 1

numQuestions = len(responses)
numCorrect = 0
wrongResponses = []

for i in range(numQuestions):
	if responses[i] == correctAnswers[i]:
		numCorrect += 1
	else:
		wrongResponses.append(i)

print("You got " + numCorrect + " out of " + numQuestions + " correct")
showWrong = input("Would you like to see what you missed? (Y/n)")
if showWrong == 'n':
	exit(0)
print("You have answered the following questions incorrectly. (Format = $questionNum: $response | $correct)")
for wrong in range(wrongResponses):
	print(wrong + ": " + responses[wrong] + " | " + correctAnswers[wrong])
