#!/usr/bin/python3.2

# Author Anthony Gargiulo
# Last modified on Wed Jan 18 02:06:33 EST 2012

def yorn(question):
	"""
	Convience function for yes or no questions
	Thanks to Posiden (Ross Delinger) for this
	"""
	answer = input("{0} (y/N): ".format(question)).lower()
	if answer == "y" or answer == "yes":
		return True
	if answer == "n" or answer == "no":
		return False
	else:
		return False

responses = []
correctAnswers = []

response = ""
quesNum = 1
correctAnswer = ""

print("Enter your responses one at a time. After the last response, enter 'end' to move on.")

while True:
	response = input(str(quesNum) + ": ")
	if response == "end":
		break
	responses.append(response)
	quesNum += 1

print("Enter the correct answers one at a time.")
numQuestions = len(responses)
quesNum = 1 #reset the question count

for i in range(numQuestions):
	correctAnswer = input(str(quesNum) + ": ")
	correctAnswers.append(correctAnswer)
	quesNum += 1

numQuestions = len(responses)
numCorrect = 0
wrongResponses = []

for i in range(numQuestions):
	if responses[i] == correctAnswers[i]:
		numCorrect += 1
	else:
		wrongResponses.append(i)

print("You got " + str(numCorrect) + " out of " + str(numQuestions)+ " correct")

# Review section
if numCorrect == numQuestions: # no wrong answers, why bother asking them to review?
	exit(0)

elif not yorn("Would you like to see what you missed?"): # Do they even want to review?
	exit(0)

print("You have answered the following questions incorrectly. (Format = $questionNum: $response | $correct)")

for wrong in wrongResponses:
	print(str(wrong + 1)+ ": " + str(responses[wrong]) + " | " + str(correctAnswers[wrong]))
